### Data Encoding
1. Nomial/OHE
2. Label and ordinal
3. Target guided ordinal

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
## Create a simple dataframe
df = pd.DataFrame({
    'color' : ['red','blue','green','green','red','green','blue','green']
})

In [6]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [8]:
## Create an instance of OneHotEncoder
encoder = OneHotEncoder()

This line of code is a one-step command to both "learn" the categories in your data and then convert them into numbers.

1. encoder.fit_transform(...)
This method combines two distinct steps that scikit-learn transformers perform:

fit: The encoder looks at the color column and identifies all unique categories (e.g., "Red", "Blue", "Green"). It builds a mapping (e.g., Red = 0, Blue = 1).

transform: It applies that mapping to the data, replacing the text strings with the corresponding numerical values.

By using fit_transform, you do both at once, which is more efficient during the initial training phase of your model.

In [9]:
# perform fit and transform
encoder.fit_transform(df[['color']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8 stored elements and shape (8, 3)>

In [11]:
encoder.fit_transform(df[['color']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

Why red got(0,0,1) not (1,0,0) because it is done alphabetically so blue got (1,0,0)

In [12]:
encoded = encoder.fit_transform(df[['color']]).toarray()

In [13]:
encode_df = pd.DataFrame(encoded)

In [14]:
encode_df

     0    1    2
0  0.0  0.0  1.0
1  1.0  0.0  0.0
2  0.0  1.0  0.0
3  0.0  1.0  0.0
4  0.0  0.0  1.0
5  0.0  1.0  0.0
6  1.0  0.0  0.0
7  0.0  1.0  0.0

In [15]:
encode_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encode_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         0.0          1.0        0.0
6         1.0          0.0        0.0
7         0.0          1.0        0.0

In [16]:
pd.concat([df,encode_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5  green         0.0          1.0        0.0
6   blue         1.0          0.0        0.0
7  green         0.0          1.0        0.0

## Note
2. Why [[]] instead of []?
This is a common point of confusion in Pandas. The difference comes down to the shape of the object being returned.

Single Brackets: df['color']
Returns: A Pandas Series.

Shape: 1-Dimensional.

Analogy: A single list of items.

Why it fails here: Scikit-learn encoders (like OneHotEncoder or OrdinalEncoder) are designed to handle multiple features at once. They strictly expect a 2D array (rows and columns), even if you are only passing in one column.

Double Brackets: df[['color']]
Returns: A Pandas DataFrame.

Shape: 2-Dimensional.

Analogy: A table that happens to have only one column.

Why we use it: This satisfies the "2D requirement" of the encoder. It tells Pandas, "Give me a subset of this table containing these columns," which keeps the result in a table (DataFrame) format.